require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ExercicesController do

  def mock_exercice(stubs={})
    @mock_exercice ||= mock_model(Exercice, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all exercices as @exercices" do
      Exercice.stub(:all) { [mock_exercice] }
      get :index
      assigns(:exercices).should eq([mock_exercice])
    end
  end

  describe "GET show" do
    it "assigns the requested exercice as @exercice" do
      Exercice.stub(:find).with("37") { mock_exercice }
      get :show, :id => "37"
      assigns(:exercice).should be(mock_exercice)
    end
  end

  describe "GET new" do
    it "assigns a new exercice as @exercice" do
      Exercice.stub(:new) { mock_exercice }
      get :new
      assigns(:exercice).should be(mock_exercice)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercice as @exercice" do
      Exercice.stub(:find).with("37") { mock_exercice }
      get :edit, :id => "37"
      assigns(:exercice).should be(mock_exercice)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created exercice as @exercice" do
        Exercice.stub(:new).with({'these' => 'params'}) { mock_exercice(:save => true) }
        post :create, :exercice => {'these' => 'params'}
        assigns(:exercice).should be(mock_exercice)
      end

      it "redirects to the created exercice" do
        Exercice.stub(:new) { mock_exercice(:save => true) }
        post :create, :exercice => {}
        response.should redirect_to(exercice_url(mock_exercice))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercice as @exercice" do
        Exercice.stub(:new).with({'these' => 'params'}) { mock_exercice(:save => false) }
        post :create, :exercice => {'these' => 'params'}
        assigns(:exercice).should be(mock_exercice)
      end

      it "re-renders the 'new' template" do
        Exercice.stub(:new) { mock_exercice(:save => false) }
        post :create, :exercice => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercice" do
        Exercice.stub(:find).with("37") { mock_exercice }
        mock_exercice.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :exercice => {'these' => 'params'}
      end

      it "assigns the requested exercice as @exercice" do
        Exercice.stub(:find) { mock_exercice(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:exercice).should be(mock_exercice)
      end

      it "redirects to the exercice" do
        Exercice.stub(:find) { mock_exercice(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(exercice_url(mock_exercice))
      end
    end

    describe "with invalid params" do
      it "assigns the exercice as @exercice" do
        Exercice.stub(:find) { mock_exercice(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:exercice).should be(mock_exercice)
      end

      it "re-renders the 'edit' template" do
        Exercice.stub(:find) { mock_exercice(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercice" do
      Exercice.stub(:find).with("37") { mock_exercice }
      mock_exercice.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the exercices list" do
      Exercice.stub(:find) { mock_exercice }
      delete :destroy, :id => "1"
      response.should redirect_to(exercices_url)
    end
  end

end
