require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProgrammesController do

  def mock_programme(stubs={})
    @mock_programme ||= mock_model(Programme, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all programmes as @programmes" do
      Programme.stub(:all) { [mock_programme] }
      get :index
      assigns(:programmes).should eq([mock_programme])
    end
  end

  describe "GET show" do
    it "assigns the requested programme as @programme" do
      Programme.stub(:find).with("37") { mock_programme }
      get :show, :id => "37"
      assigns(:programme).should be(mock_programme)
    end
  end

  describe "GET new" do
    it "assigns a new programme as @programme" do
      Programme.stub(:new) { mock_programme }
      get :new
      assigns(:programme).should be(mock_programme)
    end
  end

  describe "GET edit" do
    it "assigns the requested programme as @programme" do
      Programme.stub(:find).with("37") { mock_programme }
      get :edit, :id => "37"
      assigns(:programme).should be(mock_programme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created programme as @programme" do
        Programme.stub(:new).with({'these' => 'params'}) { mock_programme(:save => true) }
        post :create, :programme => {'these' => 'params'}
        assigns(:programme).should be(mock_programme)
      end

      it "redirects to the created programme" do
        Programme.stub(:new) { mock_programme(:save => true) }
        post :create, :programme => {}
        response.should redirect_to(programme_url(mock_programme))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved programme as @programme" do
        Programme.stub(:new).with({'these' => 'params'}) { mock_programme(:save => false) }
        post :create, :programme => {'these' => 'params'}
        assigns(:programme).should be(mock_programme)
      end

      it "re-renders the 'new' template" do
        Programme.stub(:new) { mock_programme(:save => false) }
        post :create, :programme => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested programme" do
        Programme.stub(:find).with("37") { mock_programme }
        mock_programme.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :programme => {'these' => 'params'}
      end

      it "assigns the requested programme as @programme" do
        Programme.stub(:find) { mock_programme(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:programme).should be(mock_programme)
      end

      it "redirects to the programme" do
        Programme.stub(:find) { mock_programme(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(programme_url(mock_programme))
      end
    end

    describe "with invalid params" do
      it "assigns the programme as @programme" do
        Programme.stub(:find) { mock_programme(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:programme).should be(mock_programme)
      end

      it "re-renders the 'edit' template" do
        Programme.stub(:find) { mock_programme(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested programme" do
      Programme.stub(:find).with("37") { mock_programme }
      mock_programme.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the programmes list" do
      Programme.stub(:find) { mock_programme }
      delete :destroy, :id => "1"
      response.should redirect_to(programmes_url)
    end
  end

end
